# Generated by Django 4.1.5 on 2023-01-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_first_name_student_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
