# Generated by Django 4.1.5 on 2023-01-24 07:25

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='Group Name')),
                ('start_date', models.DateField(validators=[groups.validators.ValidateGroupStartDate()], verbose_name='Start Date')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
