# Generated by Django 4.1.5 on 2023-01-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='Group Name')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Start Date')),
                ('description', models.TextField()),
            ],
        ),
    ]
